name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # 1. 打包并保存 tgz 文件名
      - id: pack
        run: |
          PKG_FILE=$(npm pack)
          echo "pkg_file=$PKG_FILE" >> $GITHUB_ENV

      # 2. 初始化 example 项目
      - run: npx @react-native-community/cli init example

      # 3. 拷贝 index.js 和 example-app
      - run: cp index.js example/
      - run: cp -r example-app example/

      # 4. 在 example 中安装打包产物
      - run: npm i ../${{ env.pkg_file }}
        working-directory: example

      # 5. 安装兼容版本 @react-native-picker/picker
      # 根据你的 React Native 版本适当调整 picker 版本号
      - run: npm i @react-native-picker/picker @react-navigation/native @react-navigation/native-stack react-native-safe-area-context react-native-screens
        working-directory: example

      # 6. 修改 gradle 配置
      - run: sed -i.backup -r 's/(enableSeparateBuildPerCPUArchitecture = )false/\1true/' build.gradle
        working-directory: example/android/app

      # 7. Clean 构建目录（推荐加上）
      - run: ./gradlew clean
        working-directory: example/android

      # 8. 构建 APK
      - run: ./gradlew assembleRelease
        working-directory: example/android

      # 9. 上传 APK
      - uses: actions/upload-artifact@v4
        with:
          name: example.apk
          path: example/android/app/build/outputs/apk/release/app-arm64-v8a-release.apk
